<?php

declare(strict_types=1);

/**
 * Writes config/deploy.build.php so site-test.php can confirm the latest deploy reached the server.
 */

$sha = getenv('GITHUB_SHA') ?: 'local';
$sha = substr(preg_replace('/[^a-f0-9]/i', '', $sha), 0, 7) ?: 'local';
$time = gmdate('Y-m-d H:i:s') . ' UTC';

$out = "<?php\n\ndeclare(strict_types=1);\n\n/** Generated by CI/CD — do not edit. */\n\n";
$out .= "if (!defined('DEPLOY_BUILD')) { define('DEPLOY_BUILD', " . var_export($sha, true) . "); }\n";
$out .= "if (!defined('DEPLOY_TIME')) { define('DEPLOY_TIME', " . var_export($time, true) . "); }\n";

$path = dirname(__DIR__) . '/config/deploy.build.php';
if (file_put_contents($path, $out) === false) {
    fwrite(STDERR, "Failed to write {$path}\n");
    exit(1);
}

fwrite(STDOUT, "Wrote config/deploy.build.php (build {$sha}).\n");
