<?php

declare(strict_types=1);

/**
 * Writes config/mail.local.php from environment variables (GitHub Actions secrets).
 * Skips when MAIL_SMTP_USER is not set.
 */

$user = getenv('MAIL_SMTP_USER');
if ($user === false || trim($user) === '') {
    fwrite(STDERR, "MAIL_SMTP_USER not set; skipping mail.local.php generation.\n");
    exit(0);
}

$pass = getenv('MAIL_SMTP_PASS') ?: '';
$from = getenv('MAIL_FROM_EMAIL') ?: $user;

if (trim($pass) === '') {
    fwrite(STDERR, "MAIL_SMTP_PASS must be set when MAIL_SMTP_USER is set.\n");
    exit(1);
}

$out = "<?php\n\ndeclare(strict_types=1);\n\n/** Generated by CI/CD — do not edit on the server; change GitHub secrets instead. */\n\n";
$out .= 'if (!defined(\'MAIL_SMTP_USER\')) { define(\'MAIL_SMTP_USER\', ' . var_export($user, true) . "); }\n";
$out .= 'if (!defined(\'MAIL_FROM_EMAIL\')) { define(\'MAIL_FROM_EMAIL\', ' . var_export($from, true) . "); }\n";
$out .= 'if (!defined(\'MAIL_SMTP_PASS\')) { define(\'MAIL_SMTP_PASS\', ' . var_export($pass, true) . "); }\n";
$out .= "if (!defined('MAIL_DEBUG')) { define('MAIL_DEBUG', false); }\n";

$path = dirname(__DIR__) . '/config/mail.local.php';
if (file_put_contents($path, $out) === false) {
    fwrite(STDERR, "Failed to write {$path}\n");
    exit(1);
}

fwrite(STDOUT, "Wrote config/mail.local.php for deployment.\n");
