<?php

declare(strict_types=1);

/**
 * Writes config/db.local.php from environment variables (GitHub Actions secrets).
 * Skips quietly when DB_HOST is not set (e.g. local runs).
 */

$host = getenv('DB_HOST');
if ($host === false || $host === '') {
    fwrite(STDERR, "DB_HOST not set; cannot deploy without database secrets.\n");
    exit(1);
}

$hostLower = strtolower($host);
if (in_array($hostLower, ['127.0.0.1', '::1'], true)) {
    fwrite(STDERR, "DB_HOST must not be 127.0.0.1 (XAMPP). Use the MySQL host from Hostinger hPanel (often localhost).\n");
    exit(1);
}

$user = getenv('DB_USER') ?: '';
$pass = getenv('DB_PASS') ?: '';
$name = getenv('DB_NAME') ?: '';

if ($user === '' || $name === '') {
    fwrite(STDERR, "DB_USER and DB_NAME must be set. Use GitHub secrets DB_USER, DB_PASS, DB_NAME (not DB_USERNAME, DB_PASSWORD, DB_DATABASE).\n");
    exit(1);
}

if ($user === 'root') {
    fwrite(STDERR, "DB_USER must be the Hostinger MySQL user (u123456789_...), not root.\n");
    exit(1);
}
$autoCreate = getenv('DB_AUTO_CREATE');
$autoCreate = ($autoCreate === false || $autoCreate === '') ? 'false' : $autoCreate;

$out = "<?php\n\ndeclare(strict_types=1);\n\n/** Generated by CI/CD — do not edit on the server; change GitHub secrets instead. */\n\n";
$out .= 'if (!defined(\'DB_HOST\')) { define(\'DB_HOST\', ' . var_export($host, true) . "); }\n";
$out .= 'if (!defined(\'DB_USER\')) { define(\'DB_USER\', ' . var_export($user, true) . "); }\n";
$out .= 'if (!defined(\'DB_PASS\')) { define(\'DB_PASS\', ' . var_export($pass, true) . "); }\n";
$out .= 'if (!defined(\'DB_NAME\')) { define(\'DB_NAME\', ' . var_export($name, true) . "); }\n";
$out .= 'if (!defined(\'DB_AUTO_CREATE\')) { define(\'DB_AUTO_CREATE\', ' . $autoCreate . "); }\n";

$path = dirname(__DIR__) . '/config/db.local.php';
if (file_put_contents($path, $out) === false) {
    fwrite(STDERR, "Failed to write {$path}\n");
    exit(1);
}

fwrite(STDOUT, "Wrote config/db.local.php for deployment.\n");
